# Generated by Django 5.2 on 2025-04-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Векторное представление трека (CLAP)', null=True, verbose_name='CLAP Эмбеддинг'),
        ),
    ]
