# Generated by Django 5.2 on 2025-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_track_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Длительность трека в секундах (определяется автоматически)', verbose_name='Длительность (сек)'),
        ),
    ]
