# Generated by Django 5.2 on 2025-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_track_duration'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={}, help_text='Необязательно. 150 символов или меньше. Только буквы, цифры и @/./+/-/_.', max_length=150, null=True, verbose_name='username'),
        ),
    ]
