# Generated by Django 5.2 on 2025-04-30 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], verbose_name='Голос')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка трека',
                'verbose_name_plural': 'Оценки треков',
                'unique_together': {('user', 'track')},
            },
        ),
    ]
