# Generated by Django 5.2 on 2025-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_likedislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoyIndexStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_instance_id', models.PositiveIntegerField(default=1, editable=False, unique=True)),
                ('needs_rebuild', models.BooleanField(default=False, verbose_name='Требуется перестроение индекса')),
                ('last_build_time', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего построения')),
            ],
            options={
                'verbose_name': 'Статус индекса Annoy',
                'verbose_name_plural': 'Статус индекса Annoy',
            },
        ),
    ]
